logging:
  # The default level of all loggers. 
  # {OFF, ERROR, WARN, INFO, DEBUG, TRACE, ALL}
  level: DEBUG

  # Console
  appenders:
    - type: console
      threshold: DEBUG
      target: stderr

login: username
password: password
